# Generated by Django 3.1.3 on 2021-01-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0002_fileupload_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='up_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='file'),
        ),
    ]
