# Generated by Django 3.1.3 on 2021-01-26 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0003_auto_20210126_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='filename',
        ),
    ]
