# Generated by Django 3.1.3 on 2021-01-27 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0005_filedownload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileDownload',
        ),
    ]
